### ISSUE TITLE
AVOID annotating types for function expression parameters Error

### ISSUE THREAD

**Issue by chilex111** [tenhobi/effective_dart#37]
**BAD:**
`var names = people.map((Person person) => person.name);`

**GOOD:**
`var names = people.map((person) => person.name);`

This is the example you gave but whenever I implement the approved method I get errors _"Missing parameter type person"_

analysis_options.yaml
```
include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "lib/generated/**"
  strong-mode: 
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - camel_case_types


```
